apiVersion: v1
kind: Service
metadata:
  name: investment-calculator-service
  namespace: investment-calculator
spec:
  selector:
    app: investment-calculator
  ports:
  - protocol: "TCP"
    port: 8082
    targetPort: 80
  type: NodePort
